server:
  port: 8086
spring:
  profiles:
    active: h2
---
spring:
  profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/tech-demo
    username: root
    password: mindzen
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
---    
spring:
  profile: h2
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
    show-sql: true
logging:
  level:
    org.hibernate.stat: debug
    org.hibernate.type: trace